
export const ADD_ITEM = 'ADD_ITEM'
export const REMOVE_ITEM = 'REMOVE_ITEM'
export const REORDER_ITEMS = 'REORDER_ITEMS'
export const CHANGE_TOAST_MESSAGE = 'CHANGE_TOAST_MESSAGE'
export const CHANGE_TOAST_STATUS = 'CHANGE_TOAST_STATUS'